# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c9b89f731e7934e28470e993ba82a3b95887302e27bd913bc0892f57f422af5b77a4ea54da7b975f1f7ceee9a779abc904bc6b54b9cdcbc1cd95a4eda5b5195

test:
  secret_key_base: d71dc84d23e736da88bf3bef441969831a6e7dc500afcc09de4598c97e38576cf306f0bb52bb9899e30fc7dc86d2cb37fb19ab5c5419f3597af4831058c819fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
